/**
 * `palette.harmony` uses `var(--*)` so values track `html.theme-*` / `html.dark` at runtime.
 *
 * Standard MUI `palette.*` keys must use **resolved** colors: MUI's styled pipeline (IconButton,
 * Button, etc.) passes palette strings through `colorManipulator`, which throws on `var(--*)`.
 * Values below mirror `harmony-styles/tokens.css` for `html.theme-ppm` and `html.theme-ppm.dark`.
 */
import type { PaletteMode } from '@mui/material/styles'
import type { HarmonyExtendedPalette } from './paletteTypes'

/** PPM light — keep in sync with `tokens.css` `html.theme-ppm` */
export const ppmStandardPaletteLight = {
  primary: {
    main: '#4C92D9',
    light: 'rgba(76, 146, 217, 0.1)',
    dark: '#3D7BC4',
    contrastText: '#FFFFFF',
  },
  secondary: {
    main: '#525969',
    light: '#6B7280',
    dark: '#373F4E',
    contrastText: '#FFFFFF',
  },
  error: {
    main: '#D83148',
    light: 'rgba(216, 49, 72, 0.1)',
    dark: '#D83148',
    contrastText: '#FFFFFF',
  },
  warning: {
    main: '#FFB020',
    light: 'rgba(255, 176, 32, 0.1)',
    dark: '#FFB020',
    contrastText: '#373F4E',
  },
  success: {
    main: '#17A871',
    light: 'rgba(23, 168, 113, 0.1)',
    dark: '#128A5E',
    contrastText: '#FFFFFF',
  },
  info: {
    main: '#3366FF',
    light: 'rgba(51, 102, 255, 0.1)',
    dark: '#3366FF',
    contrastText: '#FFFFFF',
  },
  text: {
    primary: '#373F4E',
    secondary: '#525969',
    disabled: '#6B7280',
  },
  background: {
    default: '#E2E4E9',
    paper: '#F7F8FA',
  },
  divider: '#E2E8F0',
  action: {
    active: '#373F4E',
    hover: '#E5E7EB',
    selected: 'rgba(0, 115, 230, 0.15)',
    disabled: '#6B7280',
    disabledBackground: '#EAEAEA',
    focus: '#4C92D9',
  },
} as const

/** PPM dark — keep in sync with `tokens.css` `html.theme-ppm.dark` */
export const ppmStandardPaletteDark = {
  primary: {
    main: '#59ACFF',
    light: 'rgba(89, 172, 255, 0.1)',
    dark: '#7bb8ff',
    contrastText: '#15171A',
  },
  secondary: {
    main: '#B5B5BC',
    light: '#B5B5BC',
    dark: '#FAFAFA',
    contrastText: '#15171A',
  },
  error: {
    main: '#F46286',
    light: 'rgba(244, 98, 134, 0.1)',
    dark: '#F46286',
    contrastText: '#15171A',
  },
  warning: {
    main: '#F9AF00',
    light: 'rgba(249, 175, 0, 0.1)',
    dark: '#F9AF00',
    contrastText: '#15171A',
  },
  success: {
    main: '#00E78E',
    light: 'rgba(0, 231, 142, 0.1)',
    dark: '#00C77A',
    contrastText: '#15171A',
  },
  info: {
    main: '#00ADFD',
    light: 'rgba(0, 173, 253, 0.1)',
    dark: '#00ADFD',
    contrastText: '#15171A',
  },
  text: {
    primary: '#FAFAFA',
    secondary: '#B5B5BC',
    disabled: '#B5B5BC',
  },
  background: {
    default: '#15171A',
    paper: '#1F2124',
  },
  divider: '#3A3D42',
  action: {
    active: '#FAFAFA',
    hover: '#2A2D32',
    selected: 'rgba(89, 172, 255, 0.15)',
    disabled: '#B5B5BC',
    disabledBackground: '#2A2D32',
    focus: '#59ACFF',
  },
} as const

export function ppmStandardPaletteForMode(mode: PaletteMode) {
  return mode === 'dark' ? ppmStandardPaletteDark : ppmStandardPaletteLight
}

/** @deprecated Use `ppmStandardPaletteForMode('light')` or `ppmStandardPaletteLight`. */
export const ppmStandardPaletteColors = ppmStandardPaletteLight

export const ppmHarmonyExtended: HarmonyExtendedPalette = {
  textInverse: 'var(--text-inverse)',
  borderLight: 'var(--border-light)',
  link: 'var(--link-color)',
  themePrimaryBorder: 'var(--theme-primary-border)',
  themePrimaryHoverLight: 'var(--theme-primary-hover-light)',
  navBg: 'var(--nav-bg)',
  inputBg: 'var(--input-bg)',
  inputDisabledBg: 'var(--input-disabled-bg)',
  surfaceBg: 'var(--surface-bg)',
  elevatedBg: 'var(--elevated-bg)',
  hoverBg: 'var(--hover-bg)',
  borderColor: 'var(--border-color)',
  borderFocus: 'var(--border-focus)',
  semantic: {
    successHover: 'var(--color-success-hover)',
    infoLight: 'var(--color-info-light)',
    infoBorder: 'var(--color-info-border)',
    successLight: 'var(--color-success-light)',
    successBorder: 'var(--color-success-border)',
    successBgSubtle: 'var(--color-success-bg-subtle)',
    warningLight: 'var(--color-warning-light)',
    warningBorder: 'var(--color-warning-border)',
    warningFocus: 'var(--color-warning-focus)',
    errorLight: 'var(--color-error-light)',
    errorBorder: 'var(--color-error-border)',
    errorBgSubtle: 'var(--color-error-bg-subtle)',
    errorFocus: 'var(--color-error-focus)',
  },
  themeButton: {
    primary: 'var(--theme-btn-primary)',
    primaryHover: 'var(--theme-btn-primary-hover)',
    primaryDisabledBg: 'var(--theme-btn-primary-disabled-bg)',
    primaryDisabledFg: 'var(--theme-btn-primary-disabled-fg)',
    secondaryStroke: 'var(--theme-btn-secondary-stroke)',
    secondaryHoverBg: 'var(--theme-btn-secondary-hover-bg)',
    secondaryHoverFg: 'var(--theme-btn-secondary-hover-fg)',
    secondaryHoverStroke: 'var(--theme-btn-secondary-hover-stroke)',
    secondaryDisabledFg: 'var(--theme-btn-secondary-disabled-fg)',
    tertiaryFg: 'var(--theme-btn-tertiary-fg)',
    tertiaryHoverBg: 'var(--theme-btn-tertiary-hover-bg)',
    tertiaryDisabledFg: 'var(--theme-btn-tertiary-disabled-fg)',
  },
  pageHeaderButton: {
    primary: 'var(--page-header-btn-primary)',
    hover: 'var(--page-header-btn-primary-hover)',
    disabledBg: 'var(--page-header-btn-primary-disabled-bg)',
    disabledFg: 'var(--page-header-btn-primary-disabled-fg)',
    secondaryStroke: 'var(--page-header-btn-secondary-stroke)',
    secondaryDefaultFg: 'var(--page-header-btn-secondary-default-fg)',
    secondaryHoverBg: 'var(--page-header-btn-secondary-hover-bg)',
    secondaryHoverFg: 'var(--page-header-btn-secondary-hover-fg)',
    secondaryHoverStroke: 'var(--page-header-btn-secondary-hover-stroke)',
    secondaryDisabledFg: 'var(--page-header-btn-secondary-disabled-fg)',
    tertiaryFg: 'var(--page-header-btn-tertiary-fg)',
    tertiaryHoverBg: 'var(--page-header-btn-tertiary-hover-bg)',
    tertiaryDisabledFg: 'var(--page-header-btn-tertiary-disabled-fg)',
  },
  table: {
    totalBg: 'var(--table-total-bg)',
    headerGrayBg: 'var(--table-header-gray-bg)',
    rowHoverBg: 'var(--table-row-hover-bg)',
    rowSelectedBg: 'var(--table-row-selected-bg)',
    rowSelectedHoverBg: 'var(--table-row-selected-hover-bg)',
  },
  kanban: {
    inProgressBorder: 'var(--kanban-in-progress-border)',
    doneBorder: 'var(--kanban-done-border)',
  },
  scrollbar: {
    track: 'var(--scrollbar-track)',
    thumb: 'var(--scrollbar-thumb)',
    thumbHover: 'var(--scrollbar-thumb-hover)',
  },
  cp: {
    floatingNav: {
      btnPrimary: 'var(--floating-nav-btn-primary)',
      btnPrimaryHover: 'var(--floating-nav-btn-primary-hover)',
      btnPrimaryActive: 'var(--floating-nav-btn-primary-active)',
      btnPrimaryFg: 'var(--floating-nav-btn-primary-fg)',
      btnSecondary: 'var(--floating-nav-btn-secondary)',
      btnSecondaryHoverBg: 'var(--floating-nav-btn-secondary-hover-bg)',
      btnSecondaryActiveBg: 'var(--floating-nav-btn-secondary-active-bg)',
      divider: 'var(--floating-nav-divider)',
      dividerAccent: 'var(--floating-nav-divider-accent)',
      pin: 'var(--floating-nav-pin)',
      pinHover: 'var(--floating-nav-pin-hover)',
    },
    floatingNavDark: {
      bg: 'var(--floating-nav-bg-dark)',
      border: 'var(--floating-nav-border-dark)',
      btnSecondary: 'var(--floating-nav-btn-secondary-dark)',
      btnSecondaryHoverBg: 'var(--floating-nav-btn-secondary-hover-bg-dark)',
      btnDisabledFg: 'var(--floating-nav-btn-disabled-fg-dark)',
      btnDisabledBg: 'var(--floating-nav-btn-disabled-bg-dark)',
      divider: 'var(--floating-nav-divider-dark)',
      dividerAccent: 'var(--floating-nav-divider-accent-dark)',
      pin: 'var(--floating-nav-pin-dark)',
      pinHover: 'var(--floating-nav-pin-hover-dark)',
    },
    sidebar: {
      itemFg: 'var(--cp-sidebar-item-fg)',
      itemHoverBg: 'var(--cp-sidebar-item-hover-bg)',
      sectionBorder: 'var(--cp-sidebar-section-border)',
    },
    sidebarDark: {
      sectionBg: 'var(--cp-sidebar-section-bg-dark)',
      sectionBorder: 'var(--cp-sidebar-section-border-dark)',
      itemFg: 'var(--cp-sidebar-item-fg-dark)',
      itemHoverBg: 'var(--cp-sidebar-item-hover-bg-dark)',
    },
  },
  base: {
    notificationBadgeError: 'var(--notification-badge-error)',
    alertChipBlueBg: 'var(--alert-chip-blue-bg)',
    alertChipBlueFg: 'var(--alert-chip-blue-fg)',
    alertChipErrorBg: 'var(--alert-chip-error-bg)',
    alertChipErrorFg: 'var(--alert-chip-error-fg)',
    alertChipWarningBg: 'var(--alert-chip-warning-bg)',
    alertChipWarningFg: 'var(--alert-chip-warning-fg)',
    alertChipSuccessBg: 'var(--alert-chip-success-bg)',
    alertChipSuccessFg: 'var(--alert-chip-success-fg)',
    alertChipInfoBg: 'var(--alert-chip-info-bg)',
    alertChipInfoFg: 'var(--alert-chip-info-fg)',
    alertChipOrangeBg: 'var(--alert-chip-orange-bg)',
    alertChipOrangeFg: 'var(--alert-chip-orange-fg)',
    alertChipPinkBg: 'var(--alert-chip-pink-bg)',
    alertChipPinkFg: 'var(--alert-chip-pink-fg)',
    alertChipDisabledBg: 'var(--alert-chip-disabled-bg)',
    alertChipDisabledFg: 'var(--alert-chip-disabled-fg)',
    alertChipDisabledBorder: 'var(--alert-chip-disabled-border)',
    gradientDela: 'var(--gradient-dela)',
    gradientDelaStart: 'var(--gradient-dela-start)',
    gradientDelaEnd: 'var(--gradient-dela-end)',
    gradientDelaHoverBg: 'var(--gradient-dela-hover-bg)',
    linearNew: 'var(--linear-new)',
    delaBubbleBg: 'var(--dela-bubble-bg)',
    delaUserBubbleBg: 'var(--dela-user-bubble-bg)',
    delaHeaderContentFg: 'var(--dela-header-content-fg)',
    delaPanelAvatarBg: 'var(--dela-panel-avatar-bg)',
    delaPanelContentBg: 'var(--dela-panel-content-bg)',
    delaPanelInputBg: 'var(--dela-panel-input-bg)',
    delaPanelCardBg: 'var(--dela-panel-card-bg)',
    shellFooterBg: 'var(--shell-footer-bg)',
    shellFooterTabHoverBg: 'var(--shell-footer-tab-hover-bg)',
    shellFooterTabLabelColor: 'var(--shell-footer-tab-label-color)',
    shellFooterTabIconColorActive: 'var(--shell-footer-tab-icon-color-active)',
    shellSidebarIconColorOnPrimary: 'var(--shell-sidebar-icon-color-on-primary)',
    companyPickerAcme: 'var(--company-picker-indicator-acme)',
    companyPickerOcean: 'var(--company-picker-indicator-ocean)',
    companyPickerViolet: 'var(--company-picker-indicator-violet)',
    companyPickerAzure: 'var(--company-picker-indicator-azure)',
    companyPickerSunset: 'var(--company-picker-indicator-sunset)',
    companyPickerIndicatorDefault: 'var(--company-picker-indicator-default)',
    colorErrorBgLight: 'var(--color-error-bg-light)',
    colorErrorText: 'var(--color-error-text)',
    iconFallbackBg: 'var(--icon-fallback-bg)',
    iconFallbackText: 'var(--icon-fallback-text)',
  },
}
